// ADVANTAGES OF TYPE SCRIPT
// LET'S SAY WE HAVE A CODE OF BELOW
const message = "blasphemy"
message.toLowerCase(); // String so it will return lower case version of above
// message(); // Message is not a function -- type error

// YOUR IDE MIGHT HAVE A LINTER SO IT MIGHT HAVE BEEN EASY TO FIGURE OUT THE ERROR
// BUT WHAT IF YOU HAVE BELOW
function fn(x){
    return x.flip
}
// JAVASCRIPT OR YOUR IDE DOESN'T HELP IN FINDING OUT THIS BUG
// IF YOU PASS AN OBJECT AS THE PARAMETER X TO THE FUNCTION FN WHICH HAS A PROPERTY OF FLIP THEN THE CODE RUNS FINE
// WHAT IF IT DOESN'T HAVE SUCH PROPERTY ?
// THIS IS WHERE TYPE SCRIPT COMES IN HANDY
